apiVersion: apps/v1
kind: Deployment
metadata:
  name: w-app
  namespace: encora
spec:
  selector:
    matchLabels:
      app: w-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: w-app
    spec:
      containers:
      - name: w-app
        image: dovyear2020/encora:latest
        ports:
        - containerPort: 80
