apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaweb-deployment
  namespace: encora
  labels:
    app: javaweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      labels:
        app: javaweb
    spec:
      containers:
      - name: javaweb
        image: dovyear2020/encora:latest
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
