apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaweb-deployment
  namespace: encora
  labels:
    app: javaweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      labels:
        app: javaweb
    spec:
      containers:
      - name: javaweb
        image: dovyear2020/encora:latest
        ports:
        - containerPort: 80
